### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by iandouglas** [leahriffell/viewing_party#13]
As an authenticated user,
When I visit '/dashboard'
I should see: 
- [x] 'Welcome `<username>`!' at the top of page
- [x] #9  A button to Discover Movies
- [x] #10 A friends section
- [x] #11 A viewing parties section

### Tests: 
- [x] As a logged in user:
  - Add tests
- [x] As a non-logged in user, I cannot access this page

**Comment by leahriffell** [comment]
We may just do 'welcome, email' to avoid requiring user to create a username (poor UX).
